DROP TABLE IF EXISTS `tbl_applications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tbl_applications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `application_id` varchar(150) DEFAULT NULL,
  `profile_id` int(11) NOT NULL,
  `first_name` varchar(150) DEFAULT NULL,
  `middle_name` varchar(150) DEFAULT NULL,
  `last_name` varchar(150) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `aadhaar_card_no` varchar(150) DEFAULT NULL,
  `pan_card_no` varchar(150) DEFAULT NULL,
  `mobile_no` varchar(150) DEFAULT NULL,
  `alternate_contact_no` varchar(50) DEFAULT NULL,
  `case_id` varchar(100) DEFAULT NULL,
  `branch` varchar(100) DEFAULT NULL,
  `institute_id` int(11) DEFAULT NULL,
  `loan_type_id` int(11) DEFAULT NULL,
  `applicant_type` tinyint(1) DEFAULT '1' COMMENT '1 : Salaried, 2 : Self-employed',
  `profile_type` tinyint(1) DEFAULT '1' COMMENT '1 : Resi, 2 : Office, 3 : Resi/Office',
  `area_id` int(11) DEFAULT NULL,
  `date_of_application` date DEFAULT NULL,
  `company_name` varchar(100) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `application_status` tinyint(1) DEFAULT '1' COMMENT '1 : New, 2: Inprogress, 3: Completed',
  `financial_pan_card_no` varchar(150) DEFAULT NULL,
  `financial_name` varchar(150) DEFAULT NULL,
  `financial_assessment_year` date DEFAULT NULL,
  `financial_date_of_filing` date DEFAULT NULL,
  `financial_sales` varchar(150) DEFAULT NULL,
  `financial_share_capital` varchar(150) DEFAULT NULL,
  `financial_net_profit` varchar(150) DEFAULT NULL,
  `financial_debtors` varchar(150) DEFAULT NULL,
  `financial_creditors` varchar(150) DEFAULT NULL,
  `financial_total_loans` varchar(150) DEFAULT NULL,
  `financial_depriciation` varchar(150) DEFAULT NULL,
  `bank_bank_name` varchar(150) DEFAULT NULL,
  `bank_account_holder` varchar(150) DEFAULT NULL,
  `bank_account_number` varchar(150) DEFAULT NULL,
  `bank_dated_transaction` date DEFAULT NULL,
  `bank_pan_card_no` varchar(150) DEFAULT NULL,
  `bank_current_balance` varchar(150) DEFAULT NULL,
  `bank_account_opening_date` date DEFAULT NULL,
  `bank_date_of_birth` date DEFAULT NULL,
  `bank_address` varchar(1000) DEFAULT NULL,
  `bank_narration` varchar(1000) DEFAULT NULL,
  `pan_first_name` varchar(50) DEFAULT NULL,
  `pan_last_name` varchar(50) DEFAULT NULL,
  `pan_middle_name` varchar(50) DEFAULT NULL,
  `pan_address` varchar(500) DEFAULT NULL,
  `pan_pan_no` varchar(15) DEFAULT NULL,
  `pan_dob` datetime NOT NULL,
  `pan_date_of_issue` datetime NOT NULL,
  `pan_is_complete` tinyint(1) DEFAULT '0' COMMENT '0 : Not verified, 1 : Verified',
  `pan_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `ac_first_name` varchar(50) DEFAULT NULL,
  `ac_last_name` varchar(50) DEFAULT NULL,
  `ac_middle_name` varchar(50) DEFAULT NULL,
  `ac_aadhar_no` varchar(50) DEFAULT NULL,
  `ac_dob` datetime NOT NULL,
  `ac_address` varchar(500) DEFAULT NULL,
  `ac_mobile_no` int(15) DEFAULT NULL,
  `ac_is_complete` int(15) DEFAULT NULL,
  `ac_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `passport_first_name` varchar(50) DEFAULT NULL,
  `passport_last_name` varchar(50) DEFAULT NULL,
  `passport_middle_name` varchar(50) DEFAULT NULL,
  `passport_passport_no` varchar(50) DEFAULT NULL,
  `passport_address` varchar(500) DEFAULT NULL,
  `passport_validity` datetime NOT NULL,
  `passport_date_of_issue` datetime NOT NULL,
  `passport_is_complete` int(5) DEFAULT NULL,
  `passport_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `electricity_name` varchar(50) DEFAULT NULL,
  `electricity_address` varchar(500) DEFAULT NULL,
  `electricity_is_complete` varchar(50) DEFAULT NULL,
  `electricity_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `telephone_mobile_no` int(15) DEFAULT NULL,
  `telephone_amount` int(15) DEFAULT NULL,
  `telephone_name` varchar(100) DEFAULT NULL,
  `telephone_address` text,
  `telephone_is_complete` int(50) DEFAULT NULL,
  `telephone_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `voter_first_name` varchar(50) DEFAULT NULL,
  `voter_last_name` varchar(50) DEFAULT NULL,
  `voter_middle_name` varchar(50) DEFAULT NULL,
  `voter_address` varchar(500) DEFAULT NULL,
  `voter_voter_id_no` int(15) DEFAULT NULL,
  `voter_is_complete` int(10) DEFAULT NULL,
  `voter_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `driving_name` varchar(100) DEFAULT NULL,
  `driving_driving_license_number` varchar(20) DEFAULT NULL,
  `driving_validity` datetime DEFAULT NULL,
  `driving_date_of_issue` datetime DEFAULT NULL,
  `driving_is_complete` int(10) DEFAULT NULL,
  `driving_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `company_id_name` varchar(100) DEFAULT NULL,
  `company_id_designation` varchar(100) DEFAULT NULL,
  `company_id_is_complete` int(10) DEFAULT NULL,
  `company_id_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `shop_act_name` varchar(50) DEFAULT NULL,
  `shop_act_shop_act_no` varchar(50) DEFAULT NULL,
  `shop_act_address` varchar(500) DEFAULT NULL,
  `shop_act_from_date` datetime DEFAULT NULL,
  `shop_act_till_date` datetime DEFAULT NULL,
  `shop_act_is_complete` int(10) DEFAULT NULL,
  `shop_act_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `gst_name` varchar(500) DEFAULT NULL,
  `gst_gst_no` int(10) DEFAULT NULL,
  `gst_address` varchar(500) DEFAULT NULL,
  `gst_is_complete` int(11) DEFAULT NULL,
  `gst_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `rent_agreement_met_name` varchar(100) DEFAULT NULL,
  `rent_agreement_owner_name` varchar(100) DEFAULT NULL,
  `rent_agreement_rent_amount` int(10) DEFAULT NULL,
  `rent_agreement_deposit_amount` int(10) DEFAULT NULL,
  `rent_agreement_validity` datetime DEFAULT NULL,
  `rent_agreement_is_complete` int(10) DEFAULT NULL,
  `rent_agreement_feedback` tinyint(1) DEFAULT '0' COMMENT '1 : Positive, 2 : Negative',
  `sale_agreement_seller_name` varchar(100) DEFAULT NULL,
  `sale_agreement_purchaser_name` varchar(100) DEFAULT NULL,
  `sale_agreement_address` text,
  `sale_agreement_is_complete` int(10) DEFAULT NULL,
  `sale_agreement_feedback` tinyint(1) DEFAULT '0' COMMENT '1 : Positive, 2 : Negative',
  `oc_cc_plan_cts_no` int(10) DEFAULT NULL,
  `oc_cc_plan_issuing_authority` varchar(100) DEFAULT NULL,
  `oc_cc_plan_signature` varchar(100) DEFAULT NULL,
  `oc_cc_plan_is_complete` int(10) DEFAULT NULL,
  `oc_cc_plan_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `ocr_receipt_builder_name` varchar(100) DEFAULT NULL,
  `ocr_receipt_met_person` varchar(100) DEFAULT NULL,
  `ocr_receipt_designation` varchar(100) DEFAULT NULL,
  `ocr_receipt_signature` varchar(100) DEFAULT NULL,
  `ocr_receipt_tpc` varchar(100) DEFAULT NULL,
  `ocr_receipt_landmark` varchar(200) DEFAULT NULL,
  `ocr_receipt_amount` int(10) DEFAULT NULL,
  `ocr_receipt_receipt_no` int(10) DEFAULT NULL,
  `ocr_receipt_is_complete` int(10) DEFAULT NULL,
  `ocr_receipt_feedback` tinyint(1) DEFAULT '0' COMMENT '0 : Positive, 1 : Negative',
  `created_by` int(11) DEFAULT NULL,
  `created_on` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int(11) DEFAULT NULL,
  `updated_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;